name: emotion_tracker

environment:
  sdk: ">=3.7.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.0 # Updated to the latest version
  cloud_firestore: ^5.6.4
  firebase_core: ^3.12.1
  cloud_functions: ^5.3.4
  cupertino_icons: ^1.0.8
  flutter_localizations:
    sdk: flutter
  google_fonts: ^6.2.1
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/lang/en.json
    - assets/lang/es.json
