// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBPLMR_yIDMl2O6KjyUNypWFu-8nZha2b4',
    appId: '1:969781911627:web:3c4238edc7aabe7a542dce',
    messagingSenderId: '969781911627',
    projectId: 'flutterbackend-b2ee2',
    authDomain: 'flutterbackend-b2ee2.firebaseapp.com',
    storageBucket: 'flutterbackend-b2ee2.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKcJoYk7276hUR7ZQL6AI4k5BxB1JdxZA',
    appId: '1:969781911627:android:c24b0098f00f6be9542dce',
    messagingSenderId: '969781911627',
    projectId: 'flutterbackend-b2ee2',
    storageBucket: 'flutterbackend-b2ee2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-R-yWElweMBhtxhOdY3S49FWNU8t-D_U',
    appId: '1:969781911627:ios:35437494c6b1fa99542dce',
    messagingSenderId: '969781911627',
    projectId: 'flutterbackend-b2ee2',
    storageBucket: 'flutterbackend-b2ee2.firebasestorage.app',
    iosBundleId: 'com.example.emotionTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA-R-yWElweMBhtxhOdY3S49FWNU8t-D_U',
    appId: '1:969781911627:ios:35437494c6b1fa99542dce',
    messagingSenderId: '969781911627',
    projectId: 'flutterbackend-b2ee2',
    storageBucket: 'flutterbackend-b2ee2.firebasestorage.app',
    iosBundleId: 'com.example.emotionTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBPLMR_yIDMl2O6KjyUNypWFu-8nZha2b4',
    appId: '1:969781911627:web:18e072ea78ee86ce542dce',
    messagingSenderId: '969781911627',
    projectId: 'flutterbackend-b2ee2',
    authDomain: 'flutterbackend-b2ee2.firebaseapp.com',
    storageBucket: 'flutterbackend-b2ee2.firebasestorage.app',
  );
}
